name: Blog checker

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  check-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run blog script
        run: python check_blog.py
